name: Deploy to update server
on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: creates output
              run:  sh ./build.sh
    
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
              with:
                source-directory: 'build'
                destination-github-username: 'avgothia'
                destination-repository-name: 'vcms-api'
                target-branch: 'testing'