name: Deploy to update server
on:
  push:
    branches:
      - '12-mail-an-internetwart-nach-deployment-senden'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: creates output
        run:  sh ./build.sh

      - name: Notify internetwart about changes
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_port: 465
          subject: Neues vcms update
          to: iw@avgothia.de
          from: noreply@avgothia.de
          body: Build job of ${{github.repository}} completed successfully!
